version: "3.4"

services:
  reverseproxy:
    image: nginx:stable-alpine
    container_name: ReverseProxy
    depends_on:
      - playtestbuildsapi
      - playtestwebui
    volumes:
      - /Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: on-failure

  playtestwebui:
    container_name: PlayTestWebUI
    image: dutchskull/playtestwebui
    depends_on:
      - playtestbuildsapi
    ports:
      - 6000:80

  playtestbuildsapi:
    container_name: PlayTestBuildsAPI
    image: dutchskull/playtestbuildsapi
    depends_on:
      - mongodb
    ports:
      - 5000:80
    volumes:
      - /builds:/usr/builds

  mongodb:
    container_name: MongoDB
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
    restart: on-failure

  mongo-express:
    container_name: Mongo-Express
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=Dutchskull
      - ME_CONFIG_BASICAUTH_PASSWORD=Dutchpotato
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: on-failure

volumes:
  mongo-data:
    driver: local
